version: "3.2"
services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: my-vol
        target: /data/db
volumes:
  my-vol:
    external:
      name: my-vol
