version: "3.2"
services:
  server:
    image: yararo/nodeserver:v1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    networks:
      - webnet
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    deploy:
      replicas: 3
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: /data/db
        target: /data/db
    networks:
      - webnet

networks:
  webnet:
